export default {
    signin : "http://localhost:3000/user/signIn",
    signup : "http://localhost:3000/user/signUp",
    getProducts:"http://localhost:3000/product/viewAllProducts",
    getWishlist:"http://localhost:3000/wishlist/viewAllfavoriteproduct",
    getCategories:"http://localhost:3000/category/viewAllCategory",
    removecategory:"http//localhost:3000/category/removecategory",
    addToCart:"http://localhost:3000/cart/addToCart",
    addToWishlist:"http://localhost:3000/wishlist/addWishlist", 
    userList:"http://localhost:3000/user/userList",
    deliveryBoyList:"http://localhost:3000/deliveryBoy/list",
    orderForParticularUser:"http://localhost:3000/order/viewParticularUserOrder",
    addReview:"http://localhost:3000/review/addreview",
    branlist: "http://localhost:3000/product/brand",
    getproductbybrand: "http://localhost:3000/product/getproductbybrand",
    fewcategory: "http://localhost:3000/category/fewcategory",
    viewAllOrders:"http://localhost:3000/order/viewAllOrders",
    getprductbyprice : "http://localhost:3000/product/getproductbyprice",
    getproductbyrating : "http://localhost:3000/review/getproductbyrating",
    deliveryboysignin : "http://localhost:3000/deliveryBoy/signIn",
    updateOrderStatus:"http://localhost:3000/order/updateOrderStatus",
    getOrder:"http://localhost:3000/deliverydata/getOrder",
    addProduct:"http://localhost:3000/product/addSingleProduct",
    addExcelSheet:"http://localhost:3000/product/uploadExcelSheet",
    getContactUs:"http://localhost:3000/contact/getContactUsData",
    getOrderdetail : "http://localhost:3000/order/viewAllOrders",
    deleteCategory : "http://localhost:3000/category/removecategory",
    updatePassword:"http://localhost:3000/user/updatePassword",
    getParticularDeliveryBoyOrder:"http://localhost:3000/deliverydata/deliveryBoyOrder",
    addCategory:"http://localhost:3000/category/addCategory"


}